### ISSUE TITLE
HTTPI follow_redirect mode doesn't support relative url in location 

### ISSUE THREAD

**Issue by yannrouillard** [savonrb/httpi#140]
Current follow_redirect mode try to issue a new request to the exact url provided in the Location header of the response. 
When the url is relative, this leads to an error as it is rightly recognized as a valid url.
```
ruby/1.9.1/gems/httpi-2.3.0/lib/httpi/request.rb:142:in `normalize_url!': Invalid URL: /toto (ArgumentError)
	from ruby/1.9.1/gems/httpi-2.3.0/lib/httpi/request.rb:27:in `url='
	from ruby/1.9.1/gems/httpi-2.3.0/lib/httpi.rb:163:in `request'
	from ruby/1.9.1/gems/httpi-2.3.0/lib/httpi.rb:164:in `request'
	from ruby/1.9.1/gems/httpi-2.3.0/lib/httpi.rb:125:in `get'
	from program.rb:30:in `<main>'
```

**Comment by tjarratt** [comment]
Looking forward to closing this when your PR is merged into HTTPI :+1:

**Comment by elia** [comment]
can this be closed now?

**Comment by rogerleite** [comment]
:+1:  @elia
