### ISSUE TITLE
excon adapter uses incorrect option names when passing ssl cert and key as strings

### ISSUE THREAD

**Issue by drewnichols** [savonrb/httpi#161]
When specifying an ssl cert and private key to the excon adapter as a string instead of a file excon (0.45.4 at least) expects the options to be named `:certificate` and `:private_key` instead of the current names of `:client_cert` and `:client_key`. From what I can tell these are defined in [lib/httpi/adapter/excon.rb](https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/excon.rb#L68)

Currently when I specify the cert and key as strings I get the following:

```
Excon::Errors::SocketError:
       File name too long @ rb_sysopen - -----BEGIN CERTIFICATE-----
       MIIEQzCCAyugAwIBAgIQKCMDrBR6kY5mKuo22XzeTDANBgkqhkiG9w0BAQUFADBW
       MQswCQYDVQQGEwJVUzEfMB0GA1UEChMWRmFpciBJc2FhYyBDb3Jwb3JhdGlvbjEm
       MCQGA1UEAxMdRmFpciBJc2FhYyBMZWdhY3kgU2VydmljZXMgQ0EwHhcNMTUwODI0
       MDAwMDAwWhcNMTYwODIzMjM1OTU5WjCBvzEfMB0GA1UEChQWRmFpciBJc2FhYyBD
       /fmBJQMw610MliNJqas97sRnn1tUYids/s76I6T6+rcbXJ8inlPjNcKYU7ozPcSz
       iPW4hbzu8tnnXryF8e3+VfwX9NOiimU3vDIRWRJ/hlvNSZc6Cj9D
       -----END CERTIFICATE----- (Errno::ENAMETOOLONG)
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/ssl_socket.rb:73:in `read'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/ssl_socket.rb:73:in `initialize'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:387:in `new'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:387:in `socket'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:106:in `request_call'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/middlewares/mock.rb:47:in `request_call'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/middlewares/base.rb:15:in `request_call'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/middlewares/base.rb:15:in `request_call'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/middlewares/base.rb:15:in `request_call'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:233:in `request'
     # /Users/anichols/.gem/ruby/2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:297:in `get'
     # /Users/anichols/.gem/ruby/2.1.3/bundler/gems/httpi-3d862436b967/lib/httpi/adapter/excon.rb:25:in `request'
     # /Users/anichols/.gem/ruby/2.1.3/bundler/gems/httpi-3d862436b967/lib/httpi.rb:161:in `request'
     # /Users/anichols/.gem/ruby/2.1.3/bundler/gems/httpi-3d862436b967/lib/httpi.rb:127:in `get'
     # /Users/anichols/.gem/ruby/2.1.3/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:43:in `load_from_remote'
     # /Users/anichols/.gem/ruby/2.1.3/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:33:in `resolve'
     # /Users/anichols/.gem/ruby/2.1.3/gems/wasabi-3.5.0/lib/wasabi/document.rb:142:in `xml'
     # /Users/anichols/.gem/ruby/2.1.3/gems/wasabi-3.5.0/lib/wasabi/document.rb:160:in `parse'
     # /Users/anichols/.gem/ruby/2.1.3/gems/wasabi-3.5.0/lib/wasabi/document.rb:147:in `parser'
     # /Users/anichols/.gem/ruby/2.1.3/gems/wasabi-3.5.0/lib/wasabi/document.rb:64:in `soap_actions'
     # /Users/anichols/.gem/ruby/2.1.3/gems/savon-2.10.1/lib/savon/client.rb:28:in `operations'
     # ./spec/integration/integration_spec.rb:40:in `block (4 levels) in <top (required)>'
```

**Comment by drewnichols** [comment]
After further investigation is seems that httpi is always attempting to pass to excon the client cert and key as objects where excon is expecting it to always be a string. I've submitted PR #162 to fix the issue.
