### ISSUE TITLE
httpi will fail with httpclient 2.8.0

### ISSUE THREAD

**Issue by bvogel** [savonrb/httpi#169]
Some servers (ebay.com most notably) will fail with our debian wheezy installation:

```
/home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter/httpclient.rb:28:in `rescue in request': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (HTTPI::SSLError)
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter/httpclient.rb:25:in `request'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/httpi-2.4.2/lib/httpi.rb:161:in `request'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/httpi-2.4.2/lib/httpi.rb:133:in `post'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:94:in `block in call_with_logging'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/savon-2.11.1/lib/savon/request_logger.rb:12:in `log'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:94:in `call_with_logging'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:54:in `call'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/ebay_client-0.2.0/lib/ebay_client/request.rb:35:in `execute_request'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/ebay_client-0.2.0/lib/ebay_client/request.rb:21:in `execute'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/ebay_client-0.2.0/lib/ebay_client/api.rb:34:in `dispatch'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/ebay_client-0.2.0/lib/ebay_client/api.rb:65:in `block (2 levels) in create_methods'
    from /home/rails-deploy/buddy/releases/20160503125008/lib/services/ebay_connector/trading_api.rb:40:in `get_orders'
    from /home/rails-deploy/buddy/releases/20160503125008/app/jobs/ebay_delister_task.rb:6:in `run'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/runner.rb:62:in `<top (required)>'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/runner.rb:62:in `eval'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/runner.rb:62:in `<top (required)>'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:123:in `require'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:90:in `runner'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:11:in `require'
    from bin/rails:11:in `<main>'
```

The guys over at [httpclient](https://github.com/nahi/httpclient) note in their [changelog](https://github.com/nahi/httpclient/blob/master/CHANGELOG.md) that the following would be required to remedy this issue:

```
HTTPClient.new { |c| c.ssl_config.add_trust_ca("cacert1024.pem") }
```

I can't figure out how to archive this through `HTTPI`.

**Comment by bvogel** [comment]
Currently I switched to `curb` but ultimately we would love to see `httpclient` to be a working alternative.

**Comment by rogerleite** [comment]
Hi @bvogel!

You can try to use HTTPI "secret" way to access the "native" configured client.

```
  HTTPI.get(request) do |native_client|
    native_client.ssl_config.add_trust_ca("cacert1024.pem")
  end
```

I hope that works for you!

**Comment by bvogel** [comment]
Maybe, but how would I do that using savon, which is my usecase?

**Comment by rogerleite** [comment]
In this case i don't know what to do. You can try to open an issue on Savon https://github.com/savonrb/savon/issues and ask for ideas.
