### ISSUE TITLE
Connection reset by peer using HTTPI but working on open-uri

### ISSUE THREAD

**Issue by sobrinho** [savonrb/httpi#191]
Hi there,

I'm trying to use Savon and tracked "the problem" down to HTTPI.

Easy to replicate:

```ruby
client = Savon.client(wsdl: 'https://servicoshm.saude.gov.br/cadsus/AuditoriaCadsusService/v5r0?wsdl')
puts client.operations
```

```
/Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock': Connection reset by peer (Errno::ECONNRESET) (Excon::Error::Socket)
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/socket.rb:46:in `readline'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/response.rb:63:in `parse'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/connection.rb:388:in `response'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/connection.rb:252:in `request'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/connection.rb:313:in `get'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/httpi-2.3.0/lib/httpi/adapter/excon.rb:25:in `request'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/httpi-2.3.0/lib/httpi.rb:159:in `request'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/httpi-2.3.0/lib/httpi.rb:125:in `get'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:43:in `load_from_remote'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:33:in `resolve'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/wasabi-3.5.0/lib/wasabi/document.rb:142:in `xml'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/wasabi-3.5.0/lib/wasabi/document.rb:160:in `parse'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/wasabi-3.5.0/lib/wasabi/document.rb:147:in `parser'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/wasabi-3.5.0/lib/wasabi/document.rb:64:in `soap_actions'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/savon-2.12.0/lib/savon/client.rb:28:in `operations'
        from savon.rb:7:in `<main>'
```

You can get the root issue by trying to perform a GET using HTTPI on that URL:

```ruby
puts HTTPI.get('https://servicoshm.saude.gov.br/cadsus/AuditoriaCadsusService/v5r0?wsdl')
```

```
D, [2018-03-19T15:52:50.649063 #79739] DEBUG -- : HTTPI GET request to servicoshm.saude.gov.br (excon)
/Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock': Connection reset by peer (Errno::ECONNRESET) (Excon::Error::Socket)
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/socket.rb:46:in `readline'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/response.rb:63:in `parse'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/connection.rb:388:in `response'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/connection.rb:252:in `request'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/excon-0.55.0/lib/excon/connection.rb:313:in `get'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/httpi-2.3.0/lib/httpi/adapter/excon.rb:25:in `request'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/httpi-2.3.0/lib/httpi.rb:159:in `request'
        from /Users/sobrinho/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/httpi-2.3.0/lib/httpi.rb:125:in `get'
        from savon.rb:5:in `<main>'
```

But using open-uri it works as expected:

```ruby
require 'open-uri'

puts open('https://servicoshm.saude.gov.br/cadsus/AuditoriaCadsusService/v5r0?wsdl').read
```

```
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:msfalha="http://servicos.saude.gov.br/wsdl/mensageria/falha/v5r0/msfalha" xmlns:soap11="
http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://servicos.saude.gov.br/cadsus/v5r0/auditoriacad
susservice" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="AuditoriaCadsusService" targetNamespace="http://servicos.saude.gov.br/cadsus/v5r0/auditoriacadsu
sservice">
...........
```

Obviouly I'm not in control of that URL but I'm trying to figure out what's the difference by using HTTPI (that impacts Wasabi and by that Savon).

Any ideas?

**Comment by sobrinho** [comment]
Apparently using ruby 2.4.3 fixes the issue, latest httpi and latest excon fails on 2.2.8 🤔

**Comment by samuelsimoes** [comment]
Just to complement, I had a similar problem with `httpi` and `excon`.

`HTTPI` uses `excon` as its adapter when it's available (https://github.com/savonrb/httpi/blob/ad173e28369f89d3c05ca054617eef000111e5a6/lib/httpi/adapter.rb#L16), for me, forcing the `net_http` as the adapter did the job.
